import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, rm } from 'node:fs/promises';
import { fixture } from '../fixtures/project.ts';
import { hash, writeJson } from '../../packages/core/src/fs.ts';
import {
  blueprintSchema,
  type Blueprint,
  type CompositionPlan,
} from '../../packages/core/src/composer/schemas.ts';
import { bind, keyFields } from '../../packages/core/src/composer/binding.ts';
import { planComposition, snapshot, type Snapshot } from '../../packages/core/src/composer/planner.ts';
import { declarations } from '../../packages/core/src/composer/reader.ts';

async function blueprint() {
  return blueprintSchema.parse(JSON.parse(await readFile('resources/blueprints/crm.yaml', 'utf8')));
}

function generatedSnapshot(input: Snapshot, plan: CompositionPlan, nextBlueprint: Blueprint): Snapshot {
  const sources = { ...input.sources },
    sourceInventory = { ...input.sourceInventory },
    bases = { ...input.bases };
  for (const operation of plan.operations) {
    if (operation.path.startsWith(input.sourceDir + '/')) {
      const file = operation.path.slice(input.sourceDir.length + 1);
      if (operation.content === null) {
        delete sources[file];
        delete sourceInventory[file];
      } else {
        sources[file] = operation.content;
        sourceInventory[file] = operation.after!;
      }
    } else if (operation.reason === 'retain-generated-base') bases[operation.after!] = operation.content!;
  }
  return { ...input, blueprint: nextBlueprint, state: plan.state, sources, sourceInventory, bases };
}

test('unhosting a summary allocates a distinct stable page and replans without changes', async (t) => {
  const { ctx } = await fixture();
  t.after(() => rm(ctx.root, { recursive: true, force: true }));
  const original = await blueprint();
  await writeJson(ctx.root + '/app.blueprint.yaml', original);
  const input = await snapshot(ctx, 'app.blueprint.yaml', { validation: 'source-only' }),
    initial = planComposition(input);
  assert.equal(initial.status, 'materializable');
  assert.equal(initial.allocations.CustomerList!.page, initial.allocations.CustomerSummary!.page);
  const standalone = { ...original, connections: [] },
    afterInitial = generatedSnapshot(input, initial, standalone),
    unhost = planComposition(afterInitial);
  assert.equal(unhost.status, 'materializable', JSON.stringify(unhost.diagnostics));
  assert.equal(unhost.allocations.CustomerList!.page, initial.allocations.CustomerList!.page);
  assert.notEqual(unhost.allocations.CustomerSummary!.page, unhost.allocations.CustomerList!.page);
  assert.notEqual(unhost.allocations.CustomerSummary!.page, unhost.allocations.CustomerList!.dialog);
  const afterUnhost = generatedSnapshot(afterInitial, unhost, standalone),
    pages = Object.values(afterUnhost.sources).flatMap((source) =>
      declarations(source)
        .filter((node) => node.kind === 'page')
        .map((node) => node.key),
    );
  assert.equal(new Set(pages).size, pages.length);
  const repeat = planComposition(afterUnhost);
  assert.equal(repeat.status, 'materializable');
  assert.deepEqual(repeat.allocations, unhost.allocations);
  assert.deepEqual(repeat.operations, []);
});

test('API inputs cannot read a field absent from the generated dialog', async () => {
  const value = await blueprint();
  value.blocks.CustomerList!.parameters.editableFields = ['name'];
  assert.throws(() => bind(value, value.blocks.CustomerList!), { code: 'COMMAND_INPUT_UNAVAILABLE' });
});

test('key and row version cannot share an API output argument', async () => {
  const value = await blueprint(),
    signature = value.contracts['project:save-customer']!;
  if (signature.kind !== 'command') throw new Error('Expected fixture command contract.');
  delete signature.parameters.P_ROW_VERSION;
  value.commands.SaveCustomer!.outputs.recordVersion.from = 'P_CUSTOMER_ID';
  assert.throws(() => bind(value, value.blocks.CustomerList!), { code: 'COMMAND_ARGUMENT_MISMATCH' });
});

function reverseMappings(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(reverseMappings);
  if (value && typeof value === 'object')
    return Object.fromEntries(
      Object.entries(value)
        .reverse()
        .map(([key, item]) => [key, reverseMappings(item)]),
    );
  return value;
}

test('all nested YAML mapping permutations preserve generated bytes and plan digest', async (t) => {
  const { ctx } = await fixture();
  t.after(() => rm(ctx.root, { recursive: true, force: true }));
  const original = await blueprint();
  await writeJson(ctx.root + '/app.blueprint.yaml', original);
  const input = await snapshot(ctx, 'app.blueprint.yaml', { validation: 'source-only' }),
    initial = planComposition(input),
    reordered = planComposition({ ...input, blueprint: blueprintSchema.parse(reverseMappings(original)) });
  assert.equal(initial.status, 'materializable');
  assert.equal(reordered.status, 'materializable');
  assert.equal(initial.blueprintDigest, reordered.blueprintDigest);
  assert.equal(initial.digest, reordered.digest);
  assert.deepEqual(initial.operations, reordered.operations);
});

test('ambiguous logical-field and physical-column key names fail independently of mapping order', async () => {
  const value = await blueprint(),
    entity = value.entities.Customer!;
  entity.read.fields.other = { column: 'id', type: 'integer', nullable: false };
  assert.throws(() => keyFields(entity), { code: 'KEY_MAPPING_AMBIGUOUS' });
  entity.read.fields = Object.fromEntries(Object.entries(entity.read.fields).reverse());
  assert.throws(() => keyFields(entity), { code: 'KEY_MAPPING_AMBIGUOUS' });
});

test('dialog removal checks merged postimages and preserves unmanaged consumers', async (t) => {
  const { ctx } = await fixture();
  t.after(() => rm(ctx.root, { recursive: true, force: true }));
  const original = await blueprint();
  await writeJson(ctx.root + '/app.blueprint.yaml', original);
  const input = await snapshot(ctx, 'app.blueprint.yaml', { validation: 'source-only' }),
    initial = planComposition(input),
    readOnly = structuredClone(original);
  readOnly.blocks.CustomerList!.parameters.createEnabled = false;
  readOnly.blocks.CustomerList!.parameters.editEnabled = false;
  readOnly.connections = [];
  delete readOnly.blocks.CustomerSummary;
  const afterInitial = generatedSnapshot(input, initial, readOnly),
    removal = planComposition(afterInitial),
    reportFile = Object.keys(initial.state!.owners.CustomerList!.files).find(
      (file) => !file.endsWith('_edit.apx'),
    )!,
    dialogPage = initial.allocations.CustomerList!.dialog;
  assert.equal(removal.status, 'materializable', JSON.stringify(removal.diagnostics));
  assert.ok(
    removal.operations.some(
      (operation) => operation.reason === 'remove-owned-source' && operation.path.endsWith('_edit.apx'),
    ),
  );
  const updatedReport = removal.operations.find(
    (operation) => operation.path === input.sourceDir + '/' + reportFile,
  )!;
  assert.ok(!updatedReport.content!.includes('page: ' + dialogPage));

  const localConsumer = afterInitial.sources[reportFile]!.replace(
    /\)\n$/,
    `    button manual-link (\n        behavior {\n            target {\n                page: ${dialogPage}\n            }\n        }\n    )\n)\n`,
  );
  const blocked = planComposition({
    ...afterInitial,
    sources: { ...afterInitial.sources, [reportFile]: localConsumer },
    sourceInventory: { ...afterInitial.sourceInventory, [reportFile]: hash(localConsumer) },
  });
  assert.equal(blocked.status, 'blocked');
  assert.ok(blocked.diagnostics.some((diagnostic) => diagnostic.code === 'UNKNOWN_CONSUMER_RETAINED'));
  assert.deepEqual(blocked.operations, []);
});
